import 'package:weather_app/models/weather_models/hourly_weather.dart';
import 'package:weather_app/models/weather_models/weather_condition.dart';

class HourlyData {
  static final List<HourlyWeather> dummyHourlyList = [
      HourlyWeather(
        dt: 1714046400,
        temp: 18.0,
        feelsLike: 17.5,
        pressure: 1012,
        humidity: 60,
        dewPoint: 10.0,
        uvi: 0.0,
        clouds: 20,
        visibility: 10000,
        windSpeed: 4.5,
        windDeg: 120,
        pop: 0.1, 
        weather: [
          WeatherCondition(
            id: 801,
            main: 'Clouds',
            description: 'few clouds',
            icon: '02n',
          ),
        ],
      ),
      HourlyWeather(
        dt: 1714046400,
        temp: 18.0,
        feelsLike: 17.5,
        pressure: 1012,
        humidity: 60,
        dewPoint: 10.0,
        uvi: 0.0,
        clouds: 20,
        visibility: 10000,
        windSpeed: 4.5,
        windDeg: 120,
        pop: 0.1, 
        weather: [
          WeatherCondition(
            id: 801,
            main: 'Clouds',
            description: 'few clouds',
            icon: '02n',
          ),
        ],
      ),
      HourlyWeather(
        dt: 1714046400,
        temp: 18.0,
        feelsLike: 17.5,
        pressure: 1012,
        humidity: 60,
        dewPoint: 10.0,
        uvi: 0.0,
        clouds: 20,
        visibility: 10000,
        windSpeed: 4.5,
        windDeg: 120,
        pop: 0.1,
        weather: [
          WeatherCondition(
            id: 801,
            main: 'Clouds',
            description: 'few clouds',
            icon: '02n',
          ),
        ],
      ),
      HourlyWeather(
        dt: 1714046400,
        temp: 18.0,
        feelsLike: 17.5,
        pressure: 1012,
        humidity: 60,
        dewPoint: 10.0,
        uvi: 0.0,
        clouds: 20,
        visibility: 10000,
        windSpeed: 4.5,
        windDeg: 120,
        pop: 0.1, 
        weather: [
          WeatherCondition(
            id: 801,
            main: 'Clouds',
            description: 'few clouds',
            icon: '02n',
          ),
        ],
      ),
      HourlyWeather(
        dt: 1714046400,
        temp: 18.0,
        feelsLike: 17.5,
        pressure: 1012,
        humidity: 60,
        dewPoint: 10.0,
        uvi: 0.0,
        clouds: 20,
        visibility: 10000,
        windSpeed: 4.5,
        windDeg: 120,
        pop: 0.1,
        weather: [
          WeatherCondition(
            id: 801,
            main: 'Clouds',
            description: 'few clouds',
            icon: '02n',
          ),
        ],
      ),
      HourlyWeather(
        dt: 1714050000,
        temp: 17.0,
        feelsLike: 17.0,
        pressure: 1013,
        humidity: 65,
        dewPoint: 11.0,
        uvi: 0.0,
        clouds: 80,
        visibility: 10000,
        windSpeed: 5.0,
        windDeg: 130,
        pop: 0.4,
        weather: [
          WeatherCondition(
            id: 500,
            main: 'Rain',
            description: 'light rain',
            icon: '10n',
          ),
        ],
      ),
      HourlyWeather(
        dt: 1714053600,
        temp: 16.5,
        feelsLike: 16.0,
        pressure: 1014,
        humidity: 70,
        dewPoint: 12.0,
        uvi: 0.0,
        clouds: 100,
        visibility: 8000,
        windSpeed: 6.0,
        windDeg: 140,
        pop: 0.8,
        weather: [
          WeatherCondition(
            id: 501,
            main: 'Rain',
            description: 'moderate rain',
            icon: '10n',
          ),
        ],
      ),
    ];
}